In [1]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import  StandardScaler
from sklearn.cluster import DBSCAN
import matplotlib.pyplot as plt

In [2]:

data=pd.read_csv(r'C:\Users\cheth\Assignment\Clustering\crime_data.csv')
print (data.head())

   Unnamed: 0  Murder  Assault  UrbanPop  Rape
0     Alabama    13.2      236        58  21.2
1      Alaska    10.0      263        48  44.5
2     Arizona     8.1      294        80  31.0
3    Arkansas     8.8      190        50  19.5
4  California     9.0      276        91  40.6


In [3]:
data.head()

Unnamed: 0  Murder  Assault  UrbanPop  Rape
0     Alabama    13.2      236        58  21.2
1      Alaska    10.0      263        48  44.5
2     Arizona     8.1      294        80  31.0
3    Arkansas     8.8      190        50  19.5
4  California     9.0      276        91  40.6

In [4]:
data1=data.rename(columns={"Unnamed: 0":"City"})

In [5]:
print (data1.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   City      50 non-null     object 
 1   Murder    50 non-null     float64
 2   Assault   50 non-null     int64  
 3   UrbanPop  50 non-null     int64  
 4   Rape      50 non-null     float64
dtypes: float64(2), int64(2), object(1)
memory usage: 2.1+ KB
None


In [6]:
data1.drop(['City'],axis=1,inplace=True)

In [7]:
data1

Murder  Assault  UrbanPop  Rape
0     13.2      236        58  21.2
1     10.0      263        48  44.5
2      8.1      294        80  31.0
3      8.8      190        50  19.5
4      9.0      276        91  40.6
5      7.9      204        78  38.7
6      3.3      110        77  11.1
7      5.9      238        72  15.8
8     15.4      335        80  31.9
9     17.4      211        60  25.8
10     5.3       46        83  20.2
11     2.6      120        54  14.2
12    10.4      249        83  24.0
13     7.2      113        65  21.0
14     2.2       56        57  11.3
15     6.0      115        66  18.0
16     9.7      109        52  16.3
17    15.4      249        66  22.2
18     2.1       83        51   7.8
19    11.3      300        67  27.8
20     4.4      149        85  16.3
21    12.1      255        74  35.1
22     2.7       72        66  14.9
23    16.1      259        44  17.1
24     9.0      178        70  28.2
25     6.0      109        53  16.4
26     4.3      102        62  16.5
27    12.2      252        81  46.0
28     2.1       57        56   9.5
29     7.4      159        89  18.8
30    11.4      285        70  32.1
31    11.1      254        86  26.1
32    13.0      337        45  16.1
33     0.8       45        44   7.3
34     7.3      120        75  21.4
35     6.6      151        68  20.0
36     4.9      159        67  29.3
37     6.3      106        72  14.9
38     3.4      174        87   8.3
39    14.4      279        48  22.5
40     3.8       86        45  12.8
41    13.2      188        59  26.9
42    12.7      201        80  25.5
43     3.2      120        80  22.9
44     2.2       48        32  11.2
45     8.5      156        63  20.7
46     4.0      145        73  26.2
47     5.7       81        39   9.3
48     2.6       53        66  10.8
49     6.8      161        60  15.6

In [8]:
#rray=df.values
array=data1.values

In [9]:
array

array([[ 13.2, 236. ,  58. ,  21.2],
       [ 10. , 263. ,  48. ,  44.5],
       [  8.1, 294. ,  80. ,  31. ],
       [  8.8, 190. ,  50. ,  19.5],
       [  9. , 276. ,  91. ,  40.6],
       [  7.9, 204. ,  78. ,  38.7],
       [  3.3, 110. ,  77. ,  11.1],
       [  5.9, 238. ,  72. ,  15.8],
       [ 15.4, 335. ,  80. ,  31.9],
       [ 17.4, 211. ,  60. ,  25.8],
       [  5.3,  46. ,  83. ,  20.2],
       [  2.6, 120. ,  54. ,  14.2],
       [ 10.4, 249. ,  83. ,  24. ],
       [  7.2, 113. ,  65. ,  21. ],
       [  2.2,  56. ,  57. ,  11.3],
       [  6. , 115. ,  66. ,  18. ],
       [  9.7, 109. ,  52. ,  16.3],
       [ 15.4, 249. ,  66. ,  22.2],
       [  2.1,  83. ,  51. ,   7.8],
       [ 11.3, 300. ,  67. ,  27.8],
       [  4.4, 149. ,  85. ,  16.3],
       [ 12.1, 255. ,  74. ,  35.1],
       [  2.7,  72. ,  66. ,  14.9],
       [ 16.1, 259. ,  44. ,  17.1],
       [  9. , 178. ,  70. ,  28.2],
       [  6. , 109. ,  53. ,  16.4],
       [  4.3, 102. ,  62. ,  16.5],
 

In [10]:
stscaler=StandardScaler().fit(array)

In [11]:
stscaler

StandardScaler()

In [12]:
x=stscaler.transform(array)

In [13]:
dbscan=DBSCAN(eps=1.2,min_samples=4)
dbscan.fit(x)

DBSCAN(eps=1.2, min_samples=4)

In [14]:
dbscan.labels_

array([ 0, -1,  1,  1, -1, -1,  1,  1, -1,  0,  1,  1,  1,  1,  1,  1,  1,
        0,  1,  1,  1,  1,  1,  0,  1,  1,  1, -1,  1,  1,  1,  1,  0,  1,
        1,  1,  1,  1,  1,  0,  1,  0,  1,  1,  1,  1,  1,  1,  1,  1],
      dtype=int64)

In [15]:
cl=pd.DataFrame(dbscan.labels_,columns=['clusters'])

In [16]:
df1=pd.concat([data1,cl],axis=1)

In [17]:
#Indexes of core data points
dbscan.core_sample_indices_

array([ 0,  2,  3,  6,  9, 11, 12, 13, 14, 15, 16, 17, 18, 20, 22, 24, 25,
       26, 28, 30, 31, 33, 34, 35, 36, 37, 39, 40, 41, 42, 43, 44, 45, 46,
       47, 48, 49], dtype=int64)

In [18]:
df1

Murder  Assault  UrbanPop  Rape  clusters
0     13.2      236        58  21.2         0
1     10.0      263        48  44.5        -1
2      8.1      294        80  31.0         1
3      8.8      190        50  19.5         1
4      9.0      276        91  40.6        -1
5      7.9      204        78  38.7        -1
6      3.3      110        77  11.1         1
7      5.9      238        72  15.8         1
8     15.4      335        80  31.9        -1
9     17.4      211        60  25.8         0
10     5.3       46        83  20.2         1
11     2.6      120        54  14.2         1
12    10.4      249        83  24.0         1
13     7.2      113        65  21.0         1
14     2.2       56        57  11.3         1
15     6.0      115        66  18.0         1
16     9.7      109        52  16.3         1
17    15.4      249        66  22.2         0
18     2.1       83        51   7.8         1
19    11.3      300        67  27.8         1
20     4.4      149        85  16.3         1
21    12.1      255        74  35.1         1
22     2.7       72        66  14.9         1
23    16.1      259        44  17.1         0
24     9.0      178        70  28.2         1
25     6.0      109        53  16.4         1
26     4.3      102        62  16.5         1
27    12.2      252        81  46.0        -1
28     2.1       57        56   9.5         1
29     7.4      159        89  18.8         1
30    11.4      285        70  32.1         1
31    11.1      254        86  26.1         1
32    13.0      337        45  16.1         0
33     0.8       45        44   7.3         1
34     7.3      120        75  21.4         1
35     6.6      151        68  20.0         1
36     4.9      159        67  29.3         1
37     6.3      106        72  14.9         1
38     3.4      174        87   8.3         1
39    14.4      279        48  22.5         0
40     3.8       86        45  12.8         1
41    13.2      188        59  26.9         0
42    12.7      201        80  25.5         1
43     3.2      120        80  22.9         1
44     2.2       48        32  11.2         1
45     8.5      156        63  20.7         1
46     4.0      145        73  26.2         1
47     5.7       81        39   9.3         1
48     2.6       53        66  10.8         1
49     6.8      161        60  15.6         1

In [19]:
df1.groupby('clusters').agg(['count']).reset_index()

clusters Murder Assault UrbanPop  Rape
            count   count    count count
0       -1      5       5        5     5
1        0      7       7        7     7
2        1     38      38       38    38

In [20]:
# As Epsilon value decreases the cluesters are getting reduced.
#with Epsilon 1.2 and samples 4 We get the better results