In [1]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import  StandardScaler
from sklearn.cluster import DBSCAN
import matplotlib.pyplot as plt

In [2]:
df=pd.read_csv(r'C:\Users\cheth\OneDrive\Desktop\ExcelR\Assignments\Cluestering\Wholesale customers data.csv');
print (df.head())

   Channel  Region  Fresh  Milk  Grocery  Frozen  Detergents_Paper  Delicassen
0        2       3  12669  9656     7561     214              2674        1338
1        2       3   7057  9810     9568    1762              3293        1776
2        2       3   6353  8808     7684    2405              3516        7844
3        1       3  13265  1196     4221    6404               507        1788
4        2       3  22615  5410     7198    3915              1777        5185


In [3]:
print (df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 440 entries, 0 to 439
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Channel           440 non-null    int64
 1   Region            440 non-null    int64
 2   Fresh             440 non-null    int64
 3   Milk              440 non-null    int64
 4   Grocery           440 non-null    int64
 5   Frozen            440 non-null    int64
 6   Detergents_Paper  440 non-null    int64
 7   Delicassen        440 non-null    int64
dtypes: int64(8)
memory usage: 27.6 KB
None


In [4]:
df.drop(['Channel','Region'],axis=1,inplace=True)

In [5]:
array=df.values

In [6]:
array

array([[12669,  9656,  7561,   214,  2674,  1338],
       [ 7057,  9810,  9568,  1762,  3293,  1776],
       [ 6353,  8808,  7684,  2405,  3516,  7844],
       ...,
       [14531, 15488, 30243,   437, 14841,  1867],
       [10290,  1981,  2232,  1038,   168,  2125],
       [ 2787,  1698,  2510,    65,   477,    52]], dtype=int64)

In [7]:
stscaler=StandardScaler().fit(array)

In [8]:
stscaler

StandardScaler()

In [9]:
x=stscaler.transform(array)

In [10]:
dbscan=DBSCAN(eps=.8,min_samples=3)
dbscan.fit(x)

DBSCAN(eps=0.8, min_samples=3)

In [11]:
dbscan.labels_

array([ 0,  0, -1,  0, -1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        1,  0,  0,  0,  0, -1, -1, -1,  0,  0,  0, -1,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0, -1, -1,  0,  0,  0,  0, -1,  0, -1,  0, -1,  0,
        0,  0,  0,  0,  0, -1,  0,  0,  0,  0, -1,  0,  0,  0, -1,  0,  0,
        0,  0,  0, -1,  0,  0,  0,  0,  0, -1,  0,  0,  0,  0,  0,  0,  0,
       -1, -1, -1,  0,  0,  0,  0, -1, -1,  0,  0,  0,  0,  0,  0, -1,  0,
        0, -1,  0,  0,  0,  0,  0, -1,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0, -1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0, -1, -1,  0,  0, -1,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, -1,  0,  0,  0,  0,
        0, -1,  0,  0,  0,  0,  0,  0,  0,  0,  0, -1,  0, -1,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0, -1,  0,  0,  0,  0,  0, -1,  0,
        0,  0,  0,  0,  0,  0,  0, -1,  0,  0,  0,  0, -1,  0, -1,  0,  0,
        0,  0,  0,  0,  0

In [12]:
cl=pd.DataFrame(dbscan.labels_,columns=['clusters'])

In [13]:
pd.concat([df,cl],axis=1)

Fresh   Milk  Grocery  Frozen  Detergents_Paper  Delicassen  clusters
0    12669   9656     7561     214              2674        1338         0
1     7057   9810     9568    1762              3293        1776         0
2     6353   8808     7684    2405              3516        7844        -1
3    13265   1196     4221    6404               507        1788         0
4    22615   5410     7198    3915              1777        5185        -1
..     ...    ...      ...     ...               ...         ...       ...
435  29703  12051    16027   13135               182        2204        -1
436  39228   1431      764    4510                93        2346         0
437  14531  15488    30243     437             14841        1867        -1
438  10290   1981     2232    1038               168        2125         0
439   2787   1698     2510      65               477          52         0

[440 rows x 7 columns]

In [14]:
#Indexes of core data points
dbscan.core_sample_indices_

array([  0,   1,   3,   5,   6,   7,   8,   9,  10,  11,  13,  14,  15,
        16,  17,  18,  19,  20,  21,  25,  26,  27,  29,  30,  31,  32,
        34,  35,  37,  38,  41,  42,  43,  44,  46,  48,  50,  51,  52,
        53,  54,  55,  57,  58,  59,  60,  62,  63,  64,  66,  67,  69,
        70,  72,  73,  74,  75,  76,  78,  79,  80,  81,  82,  83,  84,
        88,  89,  90,  91,  94,  95,  96,  97,  98,  99, 101, 102, 104,
       105, 106, 107, 108, 110, 111, 112, 113, 114, 115, 116, 117, 118,
       119, 120, 121, 122, 123, 124, 126, 127, 128, 129, 130, 131, 132,
       133, 134, 135, 136, 137, 138, 139, 140, 143, 144, 146, 147, 148,
       149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161,
       162, 163, 164, 166, 167, 168, 169, 170, 172, 173, 174, 175, 177,
       178, 179, 180, 182, 184, 185, 186, 187, 188, 189, 190, 191, 192,
       193, 194, 195, 197, 198, 199, 200, 203, 204, 205, 206, 207, 208,
       209, 210, 212, 213, 214, 215, 217, 219, 220, 221, 222, 22